# Generated by Django 5.0 on 2024-01-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Disciplina",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nome", models.CharField(max_length=50, unique=True)),
                (
                    "area",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("BIO", "Biológicas"),
                            ("EXA", "Exatas"),
                            ("HUM", "Humanas"),
                        ],
                        max_length=3,
                        null=True,
                    ),
                ),
                ("carga_horaria", models.IntegerField(blank=True, null=True)),
            ],
        ),
    ]
